config/routes.rb
Rails.application.routes.draw do
	root :to => "homes#index"
	post '/homes/update_tile_color'
	get '/homes/reload_tiles'
	get '/homes/leaderboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/palette.rb
class Palette < ApplicationRecord
  belongs_to :user
  validates_presence_of :code,:row,:column,:user_id

  def self.find_color_code_and_user_stamp(x,y)
    result = []
    palette = Palette.where(row: x,column: y).last
    result = [palette.code,"#{palette.user.username} #{palette.form_time_stamp}"] if palette.present?
    result
  end

  def form_time_stamp
    self.updated_at.strftime("%d-%m-%Y %H:%M:%S")
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :palettes,dependent: :destroy
  validates_presence_of :username,:ip_address

  def find_fav_color
   self.palettes.group(:code).count.sort {|a1,a2| a2[1]<=>a1[1]}.first[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_user_name

  def index; end

  def update_tile_color
    params.permit!
    params[:tiles].split(",").each do |tile|
      position = tile.split("-")[1].split("_")
      @user.palettes.create(code: params[:color_code],row: position[0],column: position[1])
    end
    respond_to :js
  end

  def reload_tiles
    respond_to :js
  end

  def leaderboard
    @users = User.joins(:palettes)
                 .select("users.*, count(palettes.id) as scount")
                 .group("users.id")
                 .order("scount DESC")
  end

  protected

  def set_user_name
    user = User.where(ip_address: request.remote_ip).last
    if user.present?
      @user = user
    else
      username = "Anonymous#{User.count+1}-#{DateTime.now.to_i}"
      @user = User.create(username: username,ip_address: request.remote_ip)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_tile_details(row,col)
    Palette.find_color_code_and_user_stamp(row,col)
  end

  def generate_tile(row,col)
    tile_info = get_tile_details(row,col)
    raw("<div onclick='toggleClass(this);' class='content' 
         id='tile-#{row}_#{col}' #{style_attributes(tile_info)}></div>")
  end

  def style_attributes(tile_info)
    "style='background-color: #{tile_info[0]}' title='#{tile_info[1]}'"
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_header.html.erb
Welcome <%= @user.username%>!
<%= link_to "Dashboard",root_path%>
<%= link_to "Leaderboard",homes_leaderboard_path%>

app/views/homes/_tiles.html.erb
<table>
  <%for row in 1..20 do %>
   <tr>
    <% for col in 1..20 do%>
      <td><%= generate_tile(row,col)%></td>
    <%end%>
   </tr>
  <%end%>
</table>

app/views/homes/index.html.erb
<div id="tiles">
  <%= render partial: "tiles"%>
</div>
<br/>
<div class="ml300">
  Color Picker: <input class="colors">
</div>
<div class="ml400 mt10">
  <button onclick="updateTileColors();">Ok</button>
  <button>Cancel</button>
</div>

app/views/homes/leaderboard.html.erb
<table class="leaderboard">
  <thead>
   <tr>
    <td>S.No</td>
    <td>Username</td>
    <td>Colors Placed</td>
    <td>Favourite Color</td>
   </tr>
  </thead>
  <tbody>
   <%@users.each_with_index do |user,index|%>
    <tr>
     <td><%= index+=1%>.</td>
     <td><%= user.username%></td>
     <td><%= user.scount%></td>
     <td style="background-color: <%= user.find_fav_color%>"></td>
    </tr>
   <%end%>
  </tbody>
</table>

app/views/homes/reload_tiles.js.erb
$('#tiles').html("<%= escape_javascript render(:partial => 'homes/tiles') %>");

app/views/homes/update_tile_color.js.erb
$("div.selected").removeClass("selected");
alert("Tiles updated sucessfully");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorPalette</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render partial: 'header'%>
    <%= yield %>
  </body>
</html>